### ISSUE TITLE
include NAMAPkit into swift  project using bridge header 

### ISSUE THREAD

**Issue by saravananNV** [neilang/NAMapKit#57] opened 2016-03-21 11:42 UTC
Hi,

   i want to implement NAMapkit in swift project using bridge header.can you please help me

**Comment by orta** [comment] 2016-03-21 11:45
@saravananNV - I've had to warn you once about being disrespectful on our issues, this is your second warning, next time I'll remove your ability to interact with this repo. Closing this issue as a dupe of #56

**Closed by orta** 2016-03-21 11:45 UTC
